language: ruby
sudo: required
services:
  - docker
matrix:
  include:
    - name: "Gaprindashvili"
      rvm: 2.3
      env: TAG=latest-gaprindashvili
    - name: "Hammer"
      rvm: 2.4
      env: TAG=latest-hammer
    - name: "Ivanchuk (master)"
      rvm: 2.5
      env: TAG=latest
    - name: "Hammer + Integration"
      rvm: 2.4
      env: TAG=latest-hammer GIT_URL=https://github.com/ThomasBuchinger/automate-example
      stage: integration
      script:
      - script/prepare_manageiq.sh
      - rake install:local
      - miq-flow deploy feature-1-f1 --provider docker --git-index 2
      - ./script/verify_import.sh
script:
  - bundle check # ManageIQ Container/Appliance needs to satisfy all dependencies
  - bundle install --with development
  - bundle exec rake travis
after_script:
  - bundle exec rake coveralls:push
